#! /bin/bash
set -e

distro=$(cat /etc/*release | grep "^ID=" | sed s/ID=//)

# Installing required packages for build
if [ "${distro}" = "fedora" ]; then
sudo dnf install make automake libtool gcc gcc-c++
sudo dnf install gsl-devel
else
# Installing required packages for build
sudo apt-get install --yes build-essential autotools-dev automake libtool
sudo apt-get install --yes libgsl0-dev
fi

# Dieharder installation
cd dieharder-src
make
cd ..
ln -s dieharder-src/install/bin/dieharder dieharder

# NIST STS installation
cd nist-sts-src
mkdir -p obj
make
cd experiments
bash create-dir-script
cd ../..
ln -s nist-sts-src/assess nist-sts

# TestU01 installation
cd testu01-src
make
cd ..
ln -s testu01-src/install/bin/TestU01 testu01

printf "\n\nInstallation complete.\n"

