#!/bin/bash
set -e

distro=$(cat /etc/*release | grep "^ID=" | sed s/ID=//)

# Installing required packages for build
if [ "${distro}" = "fedora" ]; then
sudo dnf install make automake libtool gcc gcc-c++
sudo dnf install gsl-devel
else
# Installing required packages for build
sudo apt-get install --yes build-essential autotools-dev automake libtool
sudo apt-get install --yes libgsl0-dev
fi

make all

printf "\nInstallation complete.\n"

